#!/bin/bash

# script/server: produce jekyll site of the manual

set -e

cd "$(dirname "$0")/.."

echo "==> Building book"
gitbook build

# delete old book
rm -rf mybook.pdf

echo "==> Generating PDF"
gitbook pdf . mybook.pdf

#bundle exec jekyll serve
