#!/bin/bash

# script/server: produce jekyll site of the manual

set -e

cd "$(dirname "$0")/.."

ls
cp index.html index_cache.html

echo "==> Building book"
gitbook build

cp index.html gitbook.html
cp index_cache.html index.html

# delete old book
rm -rf mybook.pdf

echo "==> Generating PDF"
gitbook pdf . mybook.pdf

#bundle exec jekyll serve
